"""Add fields for Telegram and Discord notifications

Revision ID: 4d7546dd06e0
Revises: fad2a8548917
Create Date: 2024-12-18 14:45:58.646402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7546dd06e0'
down_revision = 'fad2a8548917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_user_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('discord_user_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('telegram_chat_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('telegram_chat_id',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('discord_user_id')
        batch_op.drop_column('telegram_user_id')

    # ### end Alembic commands ###
